### ISSUE TITLE
Patient Class

### ISSUE THREAD

**Issue by PTamm** [CMPUT301F18T02/SymptoLogger#2]
Issue #15 should be completed with this.

**Comment by Kaiwenkevinz** [comment]
I know this is not my task but I accidentally did Patient Class and I don't want to delete it since it is a lot of typing.
It is [here](https://www.draw.io/?state=%7B%22folderId%22:%221mI0ouNltfNz5RDPcr3e4Y3DTOFdvbcqQ%22,%22action%22:%22create%22,%22userId%22:%22101704973443152809829%22%7D#G1m0RicnVMaeCcLnbWexEmZyrNxOi5APAm). Feel free to play with it.
